Lead Free: App/Inc/odometry.h File Reference
odometry.h File Reference
#include <stdint.h>
Classes
struct ODOMETRY
Functions
void ODOMETRY_Calculate ()
Calculate odometry.
void ODOMETRY_Reset ()
Reset sums.
const ODOMETRY * ODOMETRY_GetCurrent ()
Get current.
Function Documentation
ODOMETRY_Calculate()
void ODOMETRY_Calculate ()
Calculate odometry.
Definition at line 28 of file odometry.c.
Referenced by HAL_TIM_PeriodElapsedCallback().
ODOMETRY_GetCurrent()
const ODOMETRY* ODOMETRY_GetCurrent ()
Get current.
Definition at line 73 of file odometry.c.
Referenced by LOGGER_UpdateTarget(), RUN_Straight(), RUN_Turn(), and SERVO_Update().
ODOMETRY_Reset()
void ODOMETRY_Reset ()
Reset sums.
Definition at line 65 of file odometry.c.
Referenced by RUN_Straight(), and RUN_Turn().