Lead Free: App/Src/odometry.c File Reference
odometry.c File Reference
#include "odometry.h"
#include <math.h>
#include <float.h>
#include "sensor.h"
Macros
#define ODOMETRY_ENCODER_PPR 119.538f
#define ODOMETRY_TIRE_DIAMETER 20.9f
#define ODOMETRY_MM_PER_PULSE (((ODOMETRY_TIRE_DIAMETER) * M_PI) / ODOMETRY_ENCODER_PPR)
#define ODOMETRY_NUM_VELOCITY_SAMPLES 8
#define ODOMETRY_MASK_VELOCITY_SAMPLES (ODOMETRY_NUM_VELOCITY_SAMPLES - 1)
Functions
void ODOMETRY_Calculate ()
Calculate odometry.
void ODOMETRY_Reset ()
Reset sums.
const ODOMETRY * ODOMETRY_GetCurrent ()
Get current.
Variables
static ODOMETRY odometry = {0}
Current odometry.
static float odometryVelocitySamples [ODOMETRY_NUM_VELOCITY_SAMPLES] = {0.0f}
Velocity moving average.
static uint8_t odometryVelocitySampleHead = 0
Velocity moving average index (head)
static uint8_t odometryVelocitySampleTail = 0
Velocity moving average index (tail)
static float odometryVelocitySums = 0.0f
Vloecity sums.
Macro Definition Documentation
ODOMETRY_ENCODER_PPR
#define ODOMETRY_ENCODER_PPR 119.538f
Definition at line 10 of file odometry.c.
ODOMETRY_MASK_VELOCITY_SAMPLES
#define ODOMETRY_MASK_VELOCITY_SAMPLES (ODOMETRY_NUM_VELOCITY_SAMPLES - 1)
Definition at line 14 of file odometry.c.
ODOMETRY_MM_PER_PULSE
#define ODOMETRY_MM_PER_PULSE (((ODOMETRY_TIRE_DIAMETER) * M_PI) / ODOMETRY_ENCODER_PPR)
Definition at line 12 of file odometry.c.
ODOMETRY_NUM_VELOCITY_SAMPLES
#define ODOMETRY_NUM_VELOCITY_SAMPLES 8
Definition at line 13 of file odometry.c.
ODOMETRY_TIRE_DIAMETER
#define ODOMETRY_TIRE_DIAMETER 20.9f
Definition at line 11 of file odometry.c.
Function Documentation
ODOMETRY_Calculate()
void ODOMETRY_Calculate ()
Calculate odometry.
Definition at line 28 of file odometry.c.
Referenced by HAL_TIM_PeriodElapsedCallback().
ODOMETRY_GetCurrent()
const ODOMETRY* ODOMETRY_GetCurrent ()
Get current.
Definition at line 73 of file odometry.c.
Referenced by LOGGER_UpdateTarget(), RUN_Straight(), RUN_Turn(), and SERVO_Update().
ODOMETRY_Reset()
void ODOMETRY_Reset ()
Reset sums.
Definition at line 65 of file odometry.c.
Referenced by RUN_Straight(), and RUN_Turn().
Variable Documentation
odometry
ODOMETRY odometry = {0} static
Current odometry.
Definition at line 16 of file odometry.c.
Referenced by ODOMETRY_Calculate(), ODOMETRY_GetCurrent(), and ODOMETRY_Reset().
odometryVelocitySampleHead
uint8_t odometryVelocitySampleHead = 0 static
Velocity moving average index (head)
Definition at line 20 of file odometry.c.
Referenced by ODOMETRY_Calculate().
odometryVelocitySamples
float odometryVelocitySamples[ODOMETRY_NUM_VELOCITY_SAMPLES] = {0.0f} static
Velocity moving average.
Definition at line 18 of file odometry.c.
Referenced by ODOMETRY_Calculate().
odometryVelocitySampleTail
uint8_t odometryVelocitySampleTail = 0 static
Velocity moving average index (tail)
Definition at line 22 of file odometry.c.
Referenced by ODOMETRY_Calculate().
odometryVelocitySums
float odometryVelocitySums = 0.0f static
Vloecity sums.
Definition at line 24 of file odometry.c.
Referenced by ODOMETRY_Calculate().