mm-bluelight: App/Inc/servo.h File Reference
servo.h File Reference
Functions
void SERVO_Start (float *veloPidGain, float *angPidGain)
Start servos.
void SERVO_Reset ()
Reset servos.
void SERVO_Stop ()
Stop servos.
void SERVO_Update ()
Update servos.
void SERVO_SetTargetVelocity (float velo)
Set target velocity.
void SERVO_SetMaxVelocity (float velo)
Set target velocity.
void SERVO_SetAcceleration (float accel)
Set acceleration.
void SERVO_SetTargetAngularVelocity (float angVelo)
Set target angular velocity.
void SERVO_SetMaxAngularVelocity (float angVelo)
Set target angular velocity.
void SERVO_SetAngularAcceleration (float angAccel)
Set angular acceleration.
const float * SERVO_GetTargetVelocity ()
Get target velocity.
const float * SERVO_GetTargetAngularVelocity ()
Get target angular velocity.
Function Documentation
SERVO_GetTargetAngularVelocity()
const float* SERVO_GetTargetAngularVelocity ()
Get target angular velocity.
Definition at line 208 of file servo.c.
Referenced by LOGGER_UpdateTarget(), and RUN_Turn().
SERVO_GetTargetVelocity()
const float* SERVO_GetTargetVelocity ()
Get target velocity.
Definition at line 194 of file servo.c.
Referenced by LOGGER_UpdateTarget(), and RUN_Straight().
SERVO_Reset()
void SERVO_Reset ()
Reset servos.
Definition at line 98 of file servo.c.
Referenced by RUN_Straight(), RUN_Turn(), SERVO_Start(), and SERVO_Stop().
SERVO_SetAcceleration()
void SERVO_SetAcceleration (float accel)
Set acceleration.
Definition at line 173 of file servo.c.
Referenced by RUN_Straight().
SERVO_SetAngularAcceleration()
void SERVO_SetAngularAcceleration (float angAccel)
Set angular acceleration.
Definition at line 187 of file servo.c.
Referenced by RUN_Turn().
SERVO_SetMaxAngularVelocity()
void SERVO_SetMaxAngularVelocity (float angVelo)
Set target angular velocity.
Definition at line 215 of file servo.c.
Referenced by RUN_Turn().
SERVO_SetMaxVelocity()
void SERVO_SetMaxVelocity (float velo)
Set target velocity.
Definition at line 201 of file servo.c.
Referenced by RUN_Straight().
SERVO_SetTargetAngularVelocity()
void SERVO_SetTargetAngularVelocity (float angVelo)
Set target angular velocity.
Definition at line 180 of file servo.c.
Referenced by RUN_Turn().
SERVO_SetTargetVelocity()
void SERVO_SetTargetVelocity (float velo)
Set target velocity.
Definition at line 166 of file servo.c.
Referenced by RUN_Straight().
SERVO_Start()
void SERVO_Start (float * veloPidGain, float * angPidGain)
Start servos.
Definition at line 82 of file servo.c.
Referenced by app_main().
SERVO_Stop()
void SERVO_Stop ()
Stop servos.
Definition at line 106 of file servo.c.
Referenced by app_main().
SERVO_Update()
void SERVO_Update ()
Update servos.
Update servos.
Definition at line 120 of file servo.c.
Referenced by HAL_TIM_PeriodElapsedCallback().